image: docker:latest
services:
  - docker:dind

stages:
  - test
  - build

variables:
  REGISTRY: "registry.gitlab.com/brandonbutler/hot-copy"
  CONTAINER_IMAGE: ${REGISTRY}/${CI_PROJECT_NAME}:latest
  TEST_CONTAINER_IMAGE: ${REGISTRY}/${CI_PROJECT_NAME}:test

test:
  stage: test
  script:
    - docker build -t ${TEST_CONTAINER_IMAGE} -f 'test/Dockerfile' .
    - docker container run --rm ${TEST_CONTAINER_IMAGE}

build:
  stage: build
  before_script:
    - docker login $REGISTRY -u brandonbutler -p $CI_PASS
  script:
    - docker build -t ${CONTAINER_IMAGE} -f 'release/Dockerfile' .
    - docker push ${CONTAINER_IMAGE}